---
# All ansible-swap variables

# Ansible login user
ansible_ssh_user: root

# oh my zsh theme
zsh_theme: bureau

# Override any in your local ansible group_vars/swap.yml
# Location of swapfile
swap_path: "/swapfile"

# Hosts with low RAM may need to use a small bs size
dd_bs_size_mb: 1

# Total size for swapfile
# Count of how many passes dd should make at bs size
swap_count: 1000

# 0 to 100, how often swap is utilized
# 60 is good for desktops, 10 is good for VPS
swappiness: 10

# How often inode info is removed from cache
# Usually a frequent and costly lookup if not cached
vfs_cache_pressure: 50

# Which version of kcptun we need to download and use
kcptun_version: 20170525
# kcptun_version: 20160826
