---

- include_vars: secret.yml

- name: Install python and python-pip
  apt:
    name:
      - python
      - python-pip
    update_cache: yes

- name: Upgrade pip
  shell: pip install --upgrade pip

- name: Install setuptools package
  pip:
    name: setuptools

- name: Install shadowsocks package
  pip:
    name: shadowsocks

- name: Get ssserver path
  shell: which ssserver
  register: ssserver

- name: Configure shadowsocks server
  template: src=shadowsocks.json.j2 dest=/etc/shadowsocks.json

- name: Configure shadowsocks service
  template: src=shadowsocks.service.j2 dest=/etc/systemd/system/shadowsocks.service

- name: Restart and enable shadowsocks
  service:
    name: shadowsocks
    state: started
    enabled: yes
